# Generated by Django 5.2.8 on 2026-04-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_date_event_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_attendance',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
