# Generated by Django 5.2.8 on 2026-06-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscribed_to_event',
            field=models.BooleanField(default=False),
        ),
    ]
